name: Tests

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Setup Minikube
        uses: manusa/actions-setup-minikube@v2.4.0
        with:
          minikube version: "v1.19.0"
          kubernetes version: "v1.20.0"
          github token: ${{ secrets.GITHUB_TOKEN }}
      - name: Run Cluster
        run: kubectl apply -f k8s
      - name: Run tests
        run: |
          POD=$(kubectl get pod -l app=users -o jsonpath="{.items[0].metadata.name}")
          kubectl exec ${POD} -- pytest -v tests
