name: Tests

on: [pull_request]

jobs:
  docker:
    runs-on: ubuntu-latest
    services:
      registry:
        image: registry:2
        ports:
          - 5000:5000
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        with:
          driver-opts: network=host

      - name: Build and push to local registry
        uses: docker/build-push-action@v2
        with:
          context: users
          push: true
          file: docker/backend.dockerfile
          tags: localhost:5000/users:latest

      - name: Inspect
        run: |
          docker buildx imagetools inspect localhost:5000/users:latest

  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Setup Minikube
        uses: manusa/actions-setup-minikube@v2.4.0
        with:
          minikube version: "v1.19.0"
          kubernetes version: "v1.20.0"
          github token: ${{ secrets.GITHUB_TOKEN }}
      - name: Run Cluster
        run: kubectl apply -f k8s
      - name: Run tests
        run: |
          sleep 30
          kubectl get pods
          POD=$(kubectl get pod -l app=users -o jsonpath="{.items[0].metadata.name}")
          kubectl exec ${POD} -- pytest -v tests
